<?php

namespace AdminBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getAllCategories()
    {

        $qb=$this->getEntityManager()->createQueryBuilder();
        $qb->select('category','products')
            ->from('AdminBundle:Category','category')
            ->leftJoin('category.products','products');

        return $qb->getQuery()->getArrayResult();
    }
}
